### ISSUE TITLE
About cVAE on MNIST experiment

### ISSUE THREAD

**Issue by leekwoon** [annahdo/counterfactuals#4]
In the paper, it seems like a Conditional Variational Autoencoder (cVAE) was used for MNIST, but the code looks more like a standard VAE. Is the difference between VAE and cVAE not significant in this context?

**Comment by annahdo** [comment]
Hi leekwoon, 
thanks for the interest in our work. 

In the paper, as well as in the code, we use a simple convolutional VAE (cVAE) on the MNIST data set.
